import Head from 'next/head'
import Image from 'next/image'
import { Hero } from '../components/Hero'
import { Kelas } from '../components/Kelas'
import { KenapaCyberkarta } from '../components/KenapaCyberkarta'
import { Navbar } from '../components/Navbar'
import { PertanyaanUmum } from '../components/PertanyaanUmum'
import { Discord } from '../components/Discord'
import { SocialMedia } from '../components/SocialMedia'
import { Footer } from '../components/Footer'

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Cyberkarta Clone</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className="font-Nunito">
        <nav>
          <Navbar />
        </nav>
        <Hero />
        <Kelas />
        <KenapaCyberkarta />
        <PertanyaanUmum />
        <Discord />
        <SocialMedia />
      </main>

      <footer className="">
        <Footer />
        <div className='bg-black text-center text-cyberkarta-light'>
          This clone web is made by <a href='https://github.com/ahmadzaki2975' className='text-blue-200 underline'>Ahmad Zaki Akmal </a>
          <br />
          for education purposes only
          <br />
          <br />
          <a href="https://github.com/ahmadzaki2975/GDSC-Hacker-Assignment" className='text-blue-200 underline'>Repository</a>
        </div>
      </footer>
    </div>
  )
}
