import Head from 'next/head'
import Image from 'next/image'
import { Hero } from '../components/Hero'
import { Kelas } from '../components/Kelas'
import { Navbar } from '../components/Navbar'

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Cyberkarta Clone</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className="font-Nunito">
        <nav>
          <Navbar />
        </nav>
        <Hero />
        <Kelas />
      </main>

      <footer className="">
      </footer>
    </div>
  )
}
